### ISSUE TITLE
Default user and pass

### ISSUE THREAD

**Issue by schvabodka-man** [ymettier/rpi-roundcube#1]
Hi. What's the default user and pass for fresh installation? I can't find this in Readme

**Comment by ymettier** [comment]
Hello,

There is no user/pass for roundcube. 

When you connect to roundcube, it will send your login/password to the imap server. The imap server will authenticate you (or not).

Your question becomes : what is the user/pass for your imap server. I cannot answer this question : it depends on your imap installation.

Regards
